/* SPDX-License-Identifier: GPL-2.0 */
/* Generated by Documentation/scheduler/sched-pelt; do not modify. */

/*
 * IAMROOT, 2022.12.31:
 * - 1ms단위로 y^n에 대한 값이 [n]으로 들어가 있다.
 *   [32]에는 0.5가 들어 있는 개념(0x8000_0000)이 된다.(32은 필요없어서 없다)
 */
static const u32 runnable_avg_yN_inv[] __maybe_unused = {
	0xffffffff, 0xfa83b2da, 0xf5257d14, 0xefe4b99a, 0xeac0c6e6, 0xe5b906e6,
	0xe0ccdeeb, 0xdbfbb796, 0xd744fcc9, 0xd2a81d91, 0xce248c14, 0xc9b9bd85,
	0xc5672a10, 0xc12c4cc9, 0xbd08a39e, 0xb8fbaf46, 0xb504f333, 0xb123f581,
	0xad583ee9, 0xa9a15ab4, 0xa5fed6a9, 0xa2704302, 0x9ef5325f, 0x9b8d39b9,
	0x9837f050, 0x94f4efa8, 0x91c3d373, 0x8ea4398a, 0x8b95c1e3, 0x88980e80,
	0x85aac367, 0x82cd8698,
};

#define LOAD_AVG_PERIOD 32

/*
 * IAMROOT, 2022.12.31:
 * - y^32 = 0.5의 값인 y = 0.9786의 값에서
 *   y^n 일때 n = 0부터 무한대까지 합한 값.
 */
#define LOAD_AVG_MAX 47742
